# This is the configuration file for Bun.
# For more information, see https://bun.sh/docs/runtime/bunfig

[test]
preload = "./src/setup-tests.ts"

[coverage]
istanbul = { reporter = ["html", "text", "lcov"], directory = "./coverage" }

[install]
registry = "https://registry.npmjs.org/"
exact = false

[debug]
# Enable debug logs for specific features
dev = false
